version: '3'

services:
  database:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./database/scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${LITSCAN_USER} -d ${LITSCAN_DB}'"]
      interval: 5s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - LITSCAN_USER=${LITSCAN_USER}
      - LITSCAN_PASSWORD=${LITSCAN_PASSWORD}
      - LITSCAN_DB=${LITSCAN_DB}
    restart: unless-stopped

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ENVIRONMENT: "DOCKER"
    depends_on:
      - database
    tty: true
    restart: always

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    ports:
      - "8081:8081"
    environment:
      ENVIRONMENT: "DOCKER"
    depends_on:
      - database
    tty: true
    restart: always

volumes:
  postgres_data:

