---
- hosts: consumers
  gather_facts: No
  remote_user: centos
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "ssh/sequence_search_rsa"
  roles:
    - {role: consumer, tags: 'consumer'}
