- hosts: postgres
  gather_facts: Yes
  remote_user: centos
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "ssh/sequence_search_rsa"
  tasks:
    - name: Create database
      postgresql_db:
        state: present
        name: "reference"
      become: yes
      become_user: postgres
